version: '3.9'

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - '--configFile=/etc/traefik/traefik.yml'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/traefik.yml:/etc/traefik/traefik.yml:ro'

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web UI
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  movie-service:
    build: ./movie-service
    container_name: movie-service
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.movie-service.rule=PathPrefix(`/movies`)'
      - 'traefik.http.routers.movie-service.entrypoints=web'
      - 'traefik.http.services.movie-service.loadbalancer.server.port=8080'
    expose:
      - '8080'

  streaming-service:
    build: ./streaming-service
    container_name: streaming-service
    expose:
      - '7070'

volumes:
  minio-data:
