version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - mynetwork

volumes:
  keycloak-data:
    external: true

networks:
  mynetwork:
    external: true
