version: '3.9'

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - '80:80'
    command:
      - '--configFile=/etc/traefik/traefik.yml'
      - '8081:8081'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.yml:/etc/traefik/traefik.yml:ro'
      - './dynamic:/etc/traefik/dynamic:ro'
