version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"'
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - mynetwork

volumes:
  rabbitmq-data:
    external: true

networks:
  mynetwork:
    external: true
