http:
  routers:
    authen:
      rule: PathPrefix(`/authen`)
      service: authen-service
      entryPoints:
        - web
    login:
      rule: PathPrefix(`/login`)
      service: authen-service
      entryPoints:
        - web
    upload-movie:
      rule: 'PathPrefix(`/movies`)'
      entryPoints:
        - web
      service: movie-service
      middlewares:
        - authen-middleware

  services:
    authen-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:9090
    movie-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8080

  middlewares:
    authen-middleware:
      forwardAuth:
        address: http://host.docker.internal:9090/authen
        trustForwardHeader: true
        authResponseHeaders:
          - 'X-User'
          - 'X-Role'
