version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web UI
    volumes:
      - minio-data:/data
      - ./config/notify.json:/root/.minio/config/notify.json
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true

volumes:
  minio-data:
    external: true
