version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_DB: Movie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true

networks:
  mynetwork:
    external: true
